---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/nexaflow/public_html/
    - /home2/nexaflow/nodevenv/repositories/nexaflow/20/bin/npm install
    - /home2/nexaflow/nodevenv/repositories/nexaflow/20/bin/npm run build
    - /bin/cp -R dist/* $DEPLOYPATH