---
deployment:
  tasks:
    - source /home2/nexaflow/nodevenv/nexaflow/20/bin/activate
    - echo "Iniciando instalación..."
    - npm install
    - echo "Compilando con Vite..."
    - npm run build
    - echo "Desplegando en public_html..."
    - rm -rf ~/public_html/*
    - cp -r dist/* ~/public_html/
