---
deployment:
  tasks:
    - export NODE_ENV=production
    - source /home2/nexaflow/nodevenv/nexaflow/20/bin/activate
    - cd /home2/nexaflow/nexaflow
    - npm install
    - npx vite build
    - rm -rf /home2/nexaflow/public_html/*
    - cp -r dist/* /home2/nexaflow/public_html/