// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mvyshricuovdufooldzz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im12eXNocmljdW92ZHVmb29sZHp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NzAzOTYsImV4cCI6MjA3MDE0NjM5Nn0.dRI333U1UgOuBJcBdDI4RvULcNdB0MZU-o-eWKLJ3tk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});